sqs:
  arn: "arn:aws:sqs:us-east-2:715929228429:TestSQSDemoQueue"
  access: "**************"
  secret: "******************************************"
  url: "https://sqs.us-east-2.amazonaws.com/715929228429/TestSQSDemoQueue"
  
insight:
  url: "insights-collector.newrelic.com/v1/accounts/3338729"
  key: "NRII-OXhlA787d4I5VxXcWDtIG8gyABsr1sTG"
  keyName: "X-insert-Key"
